import 'strings.dart'; 
  // en
const Map<String, String> localizedValueEN = {
  ID.appName: 'Cold Stone',
  ID.settingLanguageDefault: 'Follow System',
  ID.stringConfirm: 'Confirm',
  ID.stringCancel: 'Cancel',
  ID.stringDiscover: 'Discover',
  ID.stringAvatar: 'Profile Photo',
  ID.stringUid: 'UID',
  ID.stringPhone: 'Phone',
  ID.stringEmail: 'Email',
  ID.stringLoginpassword: 'Login Password',
  ID.stringAccount: 'Account',
  ID.stringNickname: 'Nickname',
  ID.stringHelp: 'Help Center',
  ID.stringcommonproblem: 'Common Problem',
  ID.profileLogin: 'Login Account',
  ID.profileTool: 'Wallet Tools',
  ID.profileHelp: 'Help Center',
  ID.profileAddressBook: 'Address Book',
  ID.profileMall: 'Overview',
  ID.profileLanguage: 'Language',
  ID.profileQR: 'QR Code Capacity',
  ID.profileAbout: 'About',
  ID.profileCurrency: 'Currency',
  ID.qrStandard: 'Standard',
  ID.qrSmall: 'Small',
  ID.qrLarge: 'Large',
  ID.qrSuperLarge: 'Super Large',
  ID.qrBest: '(Recommend)',
  ID.clientNetError: 'Network abnormality, please check the network connection status',
  ID.timeOutError: 'Request timed out! Please try again later',
  ID.serverNetError: 'There is a problem with the connection to the server \nPlease try again or contact the customer service',
  ID.netConnectError: 'The network is not connected, please check and try again',
  ID.cancelConnectError: 'Request cancellation',
  ID.qrTip: 'The smaller the QR code capacity, the faster the code scanning and recognition will be, but it will increase the number of QR code pages',
  ID.emptyData: 'No data',
  ID.dataError: 'Failed to load',
  ID.reload: 'Reload',
  ID.exitApplication: 'Double click out',
  ID.releaseText: 'release refresh immediately',
  ID.refreshingText: 'Refreshing...',
  ID.completeText: 'Completed',
  ID.idleText: 'Pull down to refresh',
  ID.loadingText: 'Loading…',
  ID.pullUpToLoad: 'Pull up to load',
  ID.canLoadingText: 'Release to start loading statistics',
  ID.noDataText: 'No more data',
  ID.aboutKS: 'About',
  ID.userAgreement: 'User Agreement',
  ID.wallet: 'Wallet',
  ID.send: 'Send',
  ID.receive: 'Receive',
  ID.scan: 'Scan',
  ID.activity: 'Activity',
  ID.currencySearch: 'Search for coins',
  ID.allWallet: 'All wallets',
  ID.totalAsset: 'Total Asset',
  ID.loginString: 'Log in',
  ID.loginPhone: 'Phone Number',
  ID.loginPhoneHintText: 'Enter Phone Number',
  ID.loginEmail: 'Email',
  ID.loginEmailHintText: 'Enter Email',
  ID.loginPassword: 'Password',
  ID.loginPasswordHintText: 'Enter Password',
  ID.loginForgetPassword: 'Forgot Your Password?',
  ID.loginRegisterNew: 'Register a New Account',
  ID.loginOkPhone: 'Please enter a valid phone number',
  ID.loginOkEmail: 'Please enter your vaild email',
  ID.loginPswTip: 'Please set a password of 6-20 digits and letters',
  ID.loginSuccess: 'Success',
  ID.emptyWallethint: 'Protect asset safety, convenient to send and receive',
  ID.stringGuideTitle: 'More than surpassing, more safety',
  ID.stringGuideSubTitle: 'Hot and cold separation, private key never touches the Internet',
  ID.stringBindNow: 'Bind now',
  ID.stringBindBuyU1: 'Buy Ultra1',
  ID.stringGuideimmediatelyExperience: 'Begin',
  ID.stringAllWallet: 'All wallets',
  ID.stringDefaultWallet: 'Default',
  ID.stringBalance: 'Balance',
  ID.stringRegister: 'Register',
  ID.stringCode: 'Verification Code',
  ID.stringInputCode: 'Enter Verification Code',
  ID.stringGetCode: 'Get Code',
  ID.stringInvitationCode: 'Invitation code (optional)',
  ID.stringInputInvitationCode: 'Enter invitation code',
  ID.stringCollection: 'Receive',
  ID.stringReceiveAddress: 'Receive',
  ID.stringCopyAddress: 'Copy',
  ID.stringSaveImage: 'Save',
  ID.stringAgreement1: 'I have read and agree',
  ID.stringAgreement2: 'User Agreement',
  ID.stringHasAccount: 'Already have an account,',
  ID.stringGotoLogin: 'Log in now',
  ID.stringCopySuccess: 'Copied successfully',
  ID.stringAll: 'All',
  ID.stringTransferSend: 'Send',
  ID.stringSendAddress: 'From',
  ID.stringReciveAddress: 'To',
  ID.stringComplte: 'Completed',
  ID.stringTxFail: 'Failed',
  ID.stringReadAgreement: 'Please read and agree to the User Service Agreement',
  ID.stringOKCode: 'Please enter the correct verification code',
  ID.stringPswTip1: '6-20 characters',
  ID.stringPswTip2: 'Password cannot be empty',
  ID.stringPswTip3: 'Must contain both letters and numbers, and cannot contain special characters',
  ID.stringPswTip4: 'Same as the first password entered',
  ID.stringPswTip5: 'Confirm password cannot be empty',
  ID.stringConfirmPsw: 'Confirm password',
  ID.stringConfirmPswHit: 'Enter password again',
  ID.stringSetPassword: 'Set password',
  ID.stringRegisterSuccess: 'Register successful',
  ID.forgetTitle: 'Forgot password',
  ID.resetPasswordSuccess: 'Reset successful',
  ID.sendAddress: 'From',
  ID.sendCoin: 'Send Coin',
  ID.receiveAddress: 'To',
  ID.sendNumber: 'Amount',
  ID.sendAvailable: 'Usable',
  ID.sendButton: 'Send',
  ID.sendMaxText: 'Max',
  ID.stringChange: 'Change',
  ID.stringChangePassword: 'Change Password',
  ID.oldPassword: 'Old Password',
  ID.oldHintPassword: 'Enter the old password',
  ID.newPassword: 'New Password',
  ID.newHintPassword: 'Enter new password',
  ID.okNewPassword: 'Confirm new password',
  ID.okNewHintPassword: 'Enter the new password again',
  ID.passwordChangeSuccess: 'Change successful',
  ID.inputOkToAddress: 'Please enter the correct to address',
  ID.balanceNot: 'Insufficient balance',
  ID.broadcastSending: 'Sending, please wait...',
  ID.broadcastSuccess: 'Send successfully',
  ID.broadcastError: 'Sending failed',
  ID.broadcastReset: 'Retry',
  ID.stringBack: 'Back',
  ID.stringSendOneself: 'Send to yourself',
  ID.stringAddress: 'Address',
  ID.storageAccessNotEnabled: 'Storage access disabled',
  ID.cameraAccessNotEnabled: 'Camera access disabled',
  ID.contactPerson: 'Contact person',
  ID.stringaddress: 'address',
  ID.insertaddress: 'Enter address',
  ID.addressTag: 'Name',
  ID.addAddress: 'Add address',
  ID.usernameEditor: 'Modify Nickname',
  ID.accountback: 'Logout',
  ID.bindEmail: 'Bind Email',
  ID.stringonlineservice: 'Online Service',
  ID.stringuserfeedback: 'Feed back',
  ID.stringhelpqq: 'QQ',
  ID.stringhelpwechat: 'Wechat',
  ID.stringhelptel: 'phone',
  ID.feedbackname: 'Your name',
  ID.feedbackcontext: 'Please keep your feedbacks less than 300 words',
  ID.feedbackmode: 'Your phone or email',
  ID.submitfeedback: 'Submit',
  ID.feenotegasprice: 'The current best miner rate',
  ID.makeqr: 'Generate QR Code',
  ID.textcontent: 'text content',
  ID.contentText: 'Content text',
  ID.timesync: 'Sycn Time',
  ID.afterRefresh: 'Refresh after seconds',
};
