import 'strings.dart'; 
  // en
const Map<String, String> localizedValueEN = {
  ID.appName: 'Cold Stone',
  ID.settingLanguageDefault: 'Follow System',
  ID.stringConfirm: 'Confirm',
  ID.stringCancel: 'Cancel',
  ID.stringDiscover: 'Discover',
  ID.stringAvatar: 'Profile Photo',
  ID.stringUid: 'UID',
  ID.stringPhone: 'Phone',
  ID.stringEmail: 'Email',
  ID.stringLoginpassword: 'Login Password',
  ID.stringAccount: 'Account',
  ID.stringNickname: 'Nickname',
  ID.stringHelp: 'Help Center',
  ID.stringcommonproblem: 'Common Problem',
  ID.profileLogin: 'Login Account',
  ID.profileTool: 'Wallet Tools',
  ID.profileHelp: 'Help Center',
  ID.profileAddressBook: 'Address Book',
  ID.profileMall: 'Overview',
  ID.profileLanguage: 'Language',
  ID.profileQR: 'QR Code Capacity',
  ID.profileAbout: 'About',
  ID.profileCurrency: 'Currency',
  ID.qrStandard: 'Standard',
  ID.qrSmall: 'Small',
  ID.qrLarge: 'Large',
  ID.qrSuperLarge: 'Super Large',
  ID.qrBest: '(Recommend)',
  ID.clientNetError: 'Network abnormality, please check the network connection status',
  ID.timeOutError: 'Request timed out! Please try again later',
  ID.serverNetError: 'There is a problem with the connection to the server \nPlease try again or contact the customer service',
  ID.netConnectError: 'The network is not connected, please check and try again',
  ID.cancelConnectError: 'Request cancellation',
  ID.qrTip: 'The smaller the QR code capacity, the faster the code scanning and recognition will be, but it will increase the number of QR code pages',
  ID.emptyData: 'No data',
  ID.dataError: 'Failed to load',
  ID.reload: 'Reload',
  ID.exitApplication: 'Double click out',
  ID.releaseText: 'release refresh immediately',
  ID.refreshingText: 'Refreshing...',
  ID.completeText: 'Completed',
  ID.idleText: 'Pull down to refresh',
  ID.loadingText: 'Loading…',
  ID.pullUpToLoad: 'Pull up to load',
  ID.canLoadingText: 'Release to start loading statistics',
  ID.noDataText: 'No more data',
  ID.aboutKS: 'About',
  ID.userAgreement: 'User Agreement',
  ID.wallet: 'Wallet',
  ID.send: 'Send',
  ID.receive: 'Receive',
  ID.scan: 'Scan',
  ID.activity: 'Activity',
  ID.currencySearch: 'Search for coins',
  ID.allWallet: 'All wallets',
  ID.totalAsset: 'Total Asset',
  ID.loginString: 'Log in',
  ID.loginPhone: 'Phone Number',
  ID.loginPhoneHintText: 'Enter Phone Number',
  ID.loginEmail: 'Email',
  ID.loginEmailHintText: 'Enter Email',
  ID.loginPassword: 'Password',
  ID.loginPasswordHintText: 'Enter Password',
  ID.loginForgetPassword: 'Forgot Your Password?',
  ID.loginRegisterNew: 'Register a New Account',
  ID.loginOkPhone: 'Please enter a valid phone number',
  ID.loginOkEmail: 'Please enter your vaild email',
  ID.loginPswTip: 'Please set a password of 6-20 digits and letters',
  ID.loginSuccess: 'Success',
  ID.emptyWallethint: 'Protect asset safety, convenient to send and receive',
  ID.stringGuideTitle: 'More than surpassing, more safety',
  ID.stringGuideSubTitle: 'Hot and cold separation, private key never touches the Internet',
  ID.stringBindNow: 'Bind now',
  ID.stringBindBuyU1: 'Buy Ultra1',
  ID.stringGuideimmediatelyExperience: 'Begin',
  ID.stringAllWallet: 'All wallets',
  ID.stringDefaultWallet: 'Default',
  ID.stringBalance: 'Balance',
  ID.stringRegister: 'Register',
  ID.stringCode: 'Verification Code',
  ID.stringInputCode: 'Enter Verification Code',
  ID.stringGetCode: 'Get Code',
  ID.stringInvitationCode: 'Invitation code (optional)',
  ID.stringInputInvitationCode: 'Enter invitation code',
  ID.stringCollection: 'Receive',
  ID.stringReceiveAddress: 'Receive',
  ID.stringCopyAddress: 'Copy',
  ID.stringSaveImage: 'Save',
  ID.stringAgreement1: 'I have read and agree',
  ID.stringAgreement2: 'User Agreement',
  ID.stringHasAccount: 'Already have an account,',
  ID.stringGotoLogin: 'Log in now',
  ID.stringCopySuccess: 'Copied successfully',
  ID.stringAll: 'All',
  ID.stringTransferSend: 'Send',
  ID.stringSendAddress: 'From',
  ID.stringReciveAddress: 'To',
  ID.stringComplte: 'Completed',
  ID.stringTxFail: 'Failed',
  ID.stringReadAgreement: 'Please read and agree to the User Service Agreement',
  ID.stringOKCode: 'Please enter the correct verification code',
  ID.stringPswTip1: '6-20 characters',
  ID.stringPswTip2: 'Password cannot be empty',
  ID.stringPswTip3: 'Must contain both letters and numbers, and cannot contain special characters',
  ID.stringPswTip4: 'Same as the first password entered',
  ID.stringPswTip5: 'Confirm password cannot be empty',
  ID.stringConfirmPsw: 'Confirm password',
  ID.stringConfirmPswHit: 'Enter password again',
  ID.stringSetPassword: 'Set password',
  ID.stringRegisterSuccess: 'Register successful',
  ID.forgetTitle: 'Forgot password',
  ID.resetPasswordSuccess: 'Reset successful',
  ID.sendAddress: 'From',
  ID.sendCoin: 'Send Coin',
  ID.receiveAddress: 'To',
  ID.sendNumber: 'Amount',
  ID.sendAvailable: 'Usable',
  ID.sendButton: 'Send',
  ID.sendMaxText: 'Max',
  ID.stringChange: 'Change',
  ID.stringChangePassword: 'Change Password',
  ID.oldPassword: 'Old Password',
  ID.oldHintPassword: 'Enter the old password',
  ID.newPassword: 'New Password',
  ID.newHintPassword: 'Enter new password',
  ID.okNewPassword: 'Confirm new password',
  ID.okNewHintPassword: 'Enter the new password again',
  ID.passwordChangeSuccess: 'Change successful',
  ID.inputOkToAddress: 'Please enter the correct to address',
  ID.balanceNot: 'Insufficient balance',
  ID.broadcastSending: 'Sending, please wait...',
  ID.broadcastSuccess: 'Send successfully',
  ID.broadcastError: 'Sending failed',
  ID.broadcastReset: 'Retry',
  ID.stringBack: 'Back',
  ID.stringSendOneself: 'Send to yourself',
  ID.stringAddress: 'Address',
  ID.storageAccessNotEnabled: 'Storage access disabled',
  ID.cameraAccessNotEnabled: 'Camera access disabled',
  ID.contactPerson: 'Contact person',
  ID.insertaddress: 'Enter address',
  ID.addressTag: 'Name',
  ID.addAddress: 'Add address',
  ID.usernameEditor: 'Modify Nickname',
  ID.accountback: 'Logout',
  ID.bindEmail: 'Bind Email',
  ID.stringonlineservice: 'Online Service',
  ID.stringuserfeedback: 'Feed back',
  ID.stringhelpqq: 'QQ',
  ID.stringhelpwechat: 'Wechat',
  ID.stringhelptel: 'phone',
  ID.feedbackname: 'Your name',
  ID.feedbackcontext: 'Please keep your feedbacks less than 300 words',
  ID.feedbackmode: 'Your phone or email',
  ID.submitfeedback: 'Submit',
  ID.feenotegasprice: 'The current best miner rate',
  ID.makeqr: 'Generate QR Code',
  ID.textcontent: 'text content',
  ID.contentText: 'Content text',
  ID.timesync: 'Sycn Time',
  ID.afterRefresh: 'Refresh after @seconds seconds',
  ID.bindHardwareWallet: 'Bind hardware wallet',
  ID.verifysn: 'Anti-fake Verification',
  ID.p4verifysucess: 'Verified successfully！',
  ID.p4verifyfail: 'Verification failed!',
  ID.p4verifyRemind2: 'The device information is verified, please use the device to scan the QR code.',
  ID.p4verifyRemind: 'Scan to verify signature',
  ID.verifysnSucceedHint: 'This device is a genuine product officially sold by ColdLar, and thanks for your support.',
  ID.verifySnTime: 'First verification time:',
  ID.errwalletFake: 'This  device is not an official product of ColdLar, please use it with caution.',
  ID.stringNotices: 'Notice:',
  ID.textTimesyncInfo: 'ColdLar Ultra 1\n1.Open your hardware wallet and enter the homepage.\n2.Click \"Scan\" button to scan the QR code above.\n\nColdLar Pro 3+\n1.Open your hardware wallet and enter the homepage.\n2.Click \"Scan\" button to scan the QR code above.\n\nColdLar Pro 3\n1.Open your hardware wallet and enter the homepage.\n2.Click\"Menu\" ->\"Settings\"->\"Time\".\n3.Click\"Scan to update\"button to scan the QR code above.',
  ID.stringOfficialEmail: 'Official Email',
  ID.stringTextDial: 'Dial',
  ID.textFeedbackDialogMessage: 'Submitted successfully, thank you for your feedbacks!',
  ID.textRemind: 'Please complete the information',
  ID.textUnbounded: 'Unbounded',
  ID.textBindPhone: 'Bind Phone',
  ID.texSubmit: 'Submit',
  ID.textbindSuccess: 'Bound successfully',
  ID.manageCoin: 'Manage Coin',
  ID.supportToken: 'Added token',
  ID.nosupportToken: 'Not added token',
  ID.tokenSearch: 'symbol, name, contract',
  ID.notifiAllRead: 'All Read',
  ID.notifiTxTitle: 'Transfer',
  ID.notifiSysTitle: 'System',
  ID.textChooseChain: 'Choose a chain',
  ID.textCorrectAddress: 'Please enter the correct address',
  ID.textChain: 'Chain',
  ID.submitToken: 'Submit Token',
  ID.tokenSymbol: 'Symbol',
  ID.tokenContracts: 'ID/Contract',
  ID.enterContractsInfo: 'Enter contract address',
  ID.addContractRemind1: '1.All you need to submit is the contract of the token, after&#160;approval you can use it as normal.\n2.If the token logo needs to be showed, please send the following specific&#160;message to service@coldlar.net. \n',
  ID.addContractRemind2: '①Contract \n②logo.png (500 pixels x 500 pixels) \n③Company, personal or website related information \n④More information \n',
  ID.importTokenSymbol: 'Enter token symbol',
  ID.addressBookEditContacts: 'Edit',
  ID.addressBookDelContacts: 'Delete',
  ID.addressBookDelContactsContent: 'Are you sure to delete @contacts contact?',
  ID.addressBookDelContactsConfirm: 'Confirm deletion',
  ID.addressAlreadyExists: 'This address already exists!',
  ID.unsearchToken: 'Cannot find the specified token?',
  ID.tokenLabel: 'Type',
  ID.authFingerprintTip: 'Please press the fingerprint sensing area on the screen to verify your fingerprint.',
  ID.authContnetTextFace: 'If you need to use Face ID to unlock, please go to the system settings to enable the permission.',
  ID.authContnetTextFingerprint: 'If you need to use fingerprint unlocking, please go to the system settings to enable permissions',
  ID.authContnetTextSaveFingerprint: 'You have not entered your fingerprint yet. Please enter your fingerprint in the settings interface.',
  ID.gotoSettingTitle: 'Go to settings',
  ID.authFaceUnlock: 'Face Unlock',
  ID.authFingerprintUnlock: 'Fingerprint Unlock',
  ID.authFingerprintTap: 'Press fingerprint reader',
  ID.authFaceTitle: 'Face ID',
  ID.authFingerprintTitle: 'Fingerprint',
  ID.stringTips: 'Tip',
  ID.nfcOpen: 'Turned on',
  ID.nfcClose: 'Closed',
  ID.ultraInfo: '1. Open your hardware wallet; \n2. Go to homepage, click“Function -> Binding”；\n3. Select the chains to be bound, click“OK” button, enter the password, and generate a binding QR code; \n4. Click “Scan To Bind”button below to scan all QR code pages.',
  ID.p3PlusInfo: '1. Open your hardware wallet; \n2. Go to homepage, click“more -> binding”；\n3. Select the chains to be bound, click“OK” button, enter the password, and generate a binding QR code; \n 4. Click “Scan To Bind”button below to scan all QR code pages.',
  ID.p3Info: '1. Open the hardware wallet;\n2. Open the system menu and select "Monitor Account";\n3. Select the currency to be monitored and click the "Transfer to APP" button to transfer it using the QR code or NFC function;\n n4. Click the "Scan QR code binding" or "NFC binding" button below and follow the prompts to bind.',
  ID.p3InfoIOS: '1. Open the hardware wallet;\n2. Click "Menu"->"Monitor Account";\n3. Select the currency to be bound and click the "Transmit to Kushen APP" button to display the QR code;\n4. Click Click the "Scan QR code to bind" button at the bottom of the APP to scan all QR codes of the hardware wallet.',
  ID.p3Hint: 'If you use NFC binding, your phone needs to support both NFC and Android Bean, and turn them on. Currently, only some Android phones on the market support NFC and Android Bean functions.',
  ID.p2PlusInfo: '1. Open your hardware wallet；\n2. Click “Function” -> “Monitor Account”;\n3. Select the coins to be bound and click the “Export” button to show the QR code;\n4. Click “Scan To Bind” button below to scan the QR codes.',
  ID.p2Info: '1. Open your hardware wallet;\n2. Select coin, then jump to the “Receive” page; \n3. Enter “My Addresses” list, then select the address to be bound.\n4. Jump to the “Balance” page, then click “REFRESH” button to show the QR code;\n5. Click "Scan To Bind" button below to scan the QR code.',
  ID.p2Hint: 'Pro 2 can bind multiple addresses at a time, and the addresses will be automatically added into the “Default Wallet”.',
  ID.p1Info: '1. Open your hardware wallet；\n2. Click “Function” -> “Export Address”; \n3. Select the address to be bound and click the “Export” button to show the QR code; \n4. Click “Scan To Bind” button below to scan the QR code.',
  ID.p1Hint: 'Pro 1 can only bind one address at a time, and the address will be automatically added into the “Default Wallet”.',
  ID.addHardwareTitle: 'Add hardware wallet',
  ID.bindWalletTitle: 'Bind Wallet',
  ID.scanBindTitle: 'Scan To Bind',
  ID.pageCount: 'Page @ page is currently missing',
  ID.noinstallQQ: 'No QQ installed.',
  ID.noinstallWechat: 'No WeChat installed.',
  ID.scanResult: 'Scanning results',
  ID.copy: 'Copy',
  ID.zxingError: 'Error, Please rescan',
  ID.pleaseScanPage: 'Please scan page@scanPage',
  ID.scanNotMatchWallet: 'The scan code information does not match the currently selected wallet.',
  ID.scanError: 'Scan QR code error',
  ID.bindSucessInfo: 'You have successfully bound @wallet and can use it now!',
  ID.bindSucess: 'Bound successfully',
  ID.openWallet: 'Open Wallet',
  ID.chainManager: 'Manage',
  ID.chainSegWitP2sh: 'SegWit(P2sh)',
  ID.chainSegWit: 'SegWit',
  ID.chainLegacy: 'Legacy',
  ID.chainSegWitP2shItem: 'SegWit(P2sh)',
  ID.chainSegWitItem: 'SegWit',
  ID.chainLegacyItem: 'Legacy',
  ID.chainSelectWallet: 'Select Wallet',
  ID.chainWalletManager: 'Wallet Management',
  ID.chainAddAddress: 'Add',
  ID.chainAddressDetail: 'Show QR code',
  ID.chainEditRemark: 'Edit',
  ID.chainAddressDetailTip1: 'Only receive',
  ID.chainAddressDetailTip2: 'assets to this address',
  ID.chainAddType: 'Type',
  ID.chainAddRemark: 'Tag',
  ID.chainComplete: 'Complete',
  ID.chainAllChains: 'All chains',
  ID.chainTotalAssets: 'Total assets',
  ID.allWallets: 'All wallets',
  ID.walletInfo: 'Wallet Info',
  ID.walletName: 'Wallet Name',
  ID.bindingTime: 'Binding Time',
  ID.deviceModel: 'Device Model',
  ID.deviceId: 'Device ID',
  ID.seVersion: 'SE Version',
  ID.walletAppVersion: 'Wallet App Version',
  ID.unbind: 'Unbind',
  ID.using: 'Using',
  ID.bindFailed: 'Binding failed',
  ID.rebind: 'Rebind',
  ID.accountDelete: 'Delete',
  ID.accountDeleteTip: 'Do you want to delete the current account?',
  ID.safeSetting: 'Safety Setting',
  ID.deleteError: 'Delete failed',
  ID.deleteSuccess: 'Delete successful',
  ID.deleteSuccess: 'Delete successful',
  ID.loading: 'Loading...',
  ID.binding: 'Binding...',
};
